--Subscription table insert
insert into subscription(id, email) values(1,"test10@mail.ru");

--Event table insert
insert into event(name, description, date, eye, img) values("Astreoid","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",250300000,1,"1event.jpg");
insert into event(name, description, date, eye, img) values("Armagedon","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",200000000,1,"2event.jpg");
insert into event(name, description, date, eye, img) values("test3","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",300000000,1,"3event.jpg");
insert into event(name, description, date, eye, img) values("test4","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",400000000,1,"4event.jpg");
insert into event(name, description, date, eye, img) values("test5","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",500000000,1,"1event.jpg");

