--Subscription table insert
insert into subscription(id, email) values(1,"test10@mail.ru");

--Event table insert
insert into event(name, description, date, eye, img) values("Противостояние Нептуна ","НЕПТУН вступает в противостояние с Солнцем 27 августа, поэтому в этом месяце виден всю ночь, и это самый благоприятный период для его наблюдений. Планета перемещается попятно по созвездию Водолея в виде тусклой звезды +7,8m звездной величины с угловым диаметром около 2. Дистанция между Землей и Нептуном придерживается значения 29,0 а.е. Найти Нептун поможет бинокль или телескоп при помощи звездных карт и ясное прозрачное небо. Чтобы рассмотреть диск планеты, нужен 200-мм телескоп с увеличением от 100 крат и выше. Спутники Нептуна имеют блеск слабее +13m.",1377622800000,1,"1event.jpg");
insert into event(name, description, date, eye, img) values("Звездный дождь Персеид","Традиционно самым запоминающимся явлением второй половины лета становится звездный дождь Персеид. Обычная активность данного потока происходит в период с 17 июля по 24 августа. Персеиды являются едва ли не самым динамичным, стабильным, красивым и сильным ежегодным звездопадом. Максимум приходится на 12-13 августа, когда число метеоров достигает 100-110 в час. Для наблюдения метеорного дождя не нужны никакие астрономические приборы, поэтому насладиться ночным зрелищем может любой желающий.В 2013 году главный пик метеорного потока ожидается 12 августа с 18ч до 21ч по Всемирному времени UT. Вблизи максимума Луна будет перед первой четвертью, что создает хорошие условия для ночных наблюдений. Интенсивность этого дождя меняется год от года и зависит от плотности облака частиц в том участке шлейфа кометы, который пересекает Земля.Наблюдать поток лучше всего вдали от городских огней и не слишком лунной ночью, тогда есть шанс увидеть множество более слабых метеоров. Метеоры вылетают из радианта, который легко определить, нанеся на карту несколько метеоров из потока. Место пересечения продолжения путей метеоров от конца к началу и будет точкой радианта R. При наблюдениях метеорных дождей не обязательно смотреть на саму точку радианта. Лучше всего найти стул с откидной спинкой или шезлонг, чтобы удобнее обозревать все небо.",1376326800000,0,"2event.jpg");
insert into event(name, description, date, eye, img) values("test4","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",400000000,1,"4event.jpg");
insert into event(name, description, date, eye, img) values("test5","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt vehicula sodales. Nulla facilisi. Phasellus tempor nulla eros, non porta eros vulputate accumsan. Ut vel dictum mauris. Sed fringilla metus placerat sollicitudin aliquam. Etiam eu nulla dolor. Fusce a fermentum nisl. Suspendisse elementum bibendum arcu, sit amet viverra enim pharetra ac. Sed sodales molestie tempus. Integer id molestie nisl. Cras iaculis elit nisi, a facilisis ligula ultrices at. Nulla volutpat nunc iaculis quam suscipit volutpat. Sed tincidunt erat id porttitor ornare. In pulvinar cursus justo, ut lobortis neque commodo a.",500000000,1,"1event.jpg");

